apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: npm-pipeline
spec:
  tasks:
    - name: npminstall
      taskRef:
        name: npm-task

    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine-task

    - name: build
      runAfter:
        - tests
      taskRef:
        name: npm-task
